spring:
  hadoop:
    fsUri: hdfs://10.22.24.127:9000
    resourceManagerHost: 10.22.24.127
  yarn:
    appName: yarn-boot-sample-app
    applicationDir: /app/yarn-boot-sample-app
    client:
        files:
          - "file:target/appmaster.jar"
          - "file:target/containerapp.jar"
        launchcontext:
          archiveFile: appmaster.jar
                
    appmaster:
      containerCount: 1
      launchcontext:
          archiveFile: containerapp.jar       